
services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start
    ports:
      - 8000:8000
    env_file:
      - .envfiles/.dev-env
    environment:
      - FLASK_APP=api\srlm\run.py
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/api-docker/api

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-celeryworker
    env_file:
      - .envfiles/.dev-env
    environment:
      - FLASK_APP=api\srlm\run.py
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/api-docker/api

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-celerybeat
    env_file:
      - .envfiles/.dev-env
    environment:
      - FLASK_APP=api\srlm\run.py
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/api-docker/api

  flower:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    command: /start-flower
    env_file:
      - .envfiles/.dev-env
    environment:
      - FLASK_APP=api\srlm\run.py
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/api-docker/api

  db:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1643i8q6d2br3q8ind7354
    volumes:
      - ./compose/local/db/init:/docker-entrypoint-initdb.d
