"""linked matchtype.arena to arena.value

Revision ID: 054a8a242fd5
Revises: 10bbdb4cf1d6
Create Date: 2024-03-27 23:46:56.115393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054a8a242fd5'
down_revision = '10bbdb4cf1d6'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchtype', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'arena', ['arena'], ['value'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchtype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

