"""empty message

Revision ID: 09ddd077fa51
Revises: db2fc555229e
Create Date: 2024-03-23 22:00:00.581391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09ddd077fa51'
down_revision = 'db2fc555229e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_type_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('season_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'matchtype', ['match_type_id'], ['id'])
        batch_op.drop_column('match_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_type', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('season_ibfk_2', 'matchtype', ['match_type'], ['id'])
        batch_op.drop_column('match_type_id')

    # ### end Alembic commands ###
