"""empty message

Revision ID: 10bbdb4cf1d6
Revises: a2210cbd1f07
Create Date: 2024-03-27 20:54:06.176720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bbdb4cf1d6'
down_revision = 'a2210cbd1f07'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_index('ix_division_acronym')

    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.create_index('ix_division_acronym', ['acronym'], unique=False)

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

