"""made reason column longer in match_review

Revision ID: 2705f60fc76f
Revises: 4489d9574008
Create Date: 2024-04-05 19:47:05.173236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2705f60fc76f'
down_revision = '4489d9574008'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

