"""empty message

Revision ID: 355f64542422
Revises: 9a8e1ed1e699
Create Date: 2024-03-25 23:33:49.018635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355f64542422'
down_revision = '9a8e1ed1e699'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_discord_discord_id'), ['discord_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reset_pass',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('reset_pass',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('discord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_discord_id'))
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

