"""twitch models and external apps

Revision ID: 363ba563a7b5
Revises: 355f64542422
Create Date: 2024-03-26 15:50:17.049047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ba563a7b5'
down_revision = '355f64542422'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_secret', sa.String(length=128), nullable=True),
    sa.Column('grant_type', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('token_type', sa.String(length=128), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('twitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twitch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twitch_twitch_id'), ['twitch_id'], unique=True)

    with op.batch_alter_table('discord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('steam_id')

    with op.batch_alter_table('discord', schema=None) as batch_op:
        batch_op.drop_column('token_expiration')

    with op.batch_alter_table('twitch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twitch_twitch_id'))

    op.drop_table('twitch')
    op.drop_table('external_app')
    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

