"""removed match_review.resolved_on

Revision ID: 36f7c7f5c935
Revises: ee7faff8156e
Create Date: 2024-05-20 17:23:06.726246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f7c7f5c935'
down_revision = 'ee7faff8156e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema='league_manager') as batch_op:
        batch_op.drop_column('resolved_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema='league_manager') as batch_op:
        batch_op.add_column(sa.Column('resolved_on', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
