"""added task_id to lobby table

Revision ID: 5e0d45e48cbd
Revises: 2d8ea3bc062b
Create Date: 2024-04-02 19:54:24.995027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0d45e48cbd'
down_revision = '2d8ea3bc062b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobby', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

