"""added processed(boolean) column to match_data

Revision ID: 5ffcaa30349f
Revises: 5e0d45e48cbd
Create Date: 2024-04-02 22:04:39.851087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffcaa30349f'
down_revision = '5e0d45e48cbd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.drop_column('processed')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

