"""changes to matchdata and playermatchdata

Revision ID: 831cabb33357
Revises: 5ffcaa30349f
Create Date: 2024-04-02 22:59:35.935396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '831cabb33357'
down_revision = '5ffcaa30349f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('gamemode', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('arena', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('home_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('winner', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('current_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('periods_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('custom_mercy_rule', sa.String(length=16), nullable=False))

    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('player_match_data_ibfk_3', type_='foreignkey')
        batch_op.drop_column('period')
        batch_op.drop_column('comments')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_date')
        batch_op.drop_column('recorded_date')
        batch_op.drop_column('valid')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recorded_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('reviewed_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comments', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('player_match_data_ibfk_3', 'user', ['reviewed_by_id'], ['id'])
        batch_op.drop_column('accepted')

    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.drop_column('custom_mercy_rule')
        batch_op.drop_column('periods_enabled')
        batch_op.drop_column('current_period')
        batch_op.drop_column('winner')
        batch_op.drop_column('away_score')
        batch_op.drop_column('home_score')
        batch_op.drop_column('arena')
        batch_op.drop_column('created')
        batch_op.drop_column('gamemode')
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

