"""more changes to support match data

Revision ID: 85cc919b2356
Revises: 831cabb33357
Create Date: 2024-04-02 23:21:43.635682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85cc919b2356'
down_revision = '831cabb33357'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('end_reason', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=10), nullable=True))

    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.drop_column('accepted')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('accepted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('end_reason')
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

