"""empty message

Revision ID: a2210cbd1f07
Revises: 363ba563a7b5
Create Date: 2024-03-26 23:20:22.186261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2210cbd1f07'
down_revision = '363ba563a7b5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=5), nullable=False))
        batch_op.create_index(batch_op.f('ix_division_acronym'), ['acronym'], unique=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_division_acronym'))
        batch_op.drop_column('acronym')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

