"""empty message

Revision ID: b90ab4d24607
Revises: 
Create Date: 2024-03-24 19:12:58.692382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90ab4d24607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=34), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorized_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorized_app_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_authorized_app_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorized_app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorized_app_token'))
        batch_op.drop_index(batch_op.f('ix_authorized_app_name'))

    op.drop_table('authorized_app')
    # ### end Alembic commands ###

