"""add match_review.resolved_on back as datetime instead of int

Revision ID: be7d29981b84
Revises: 36f7c7f5c935
Create Date: 2024-05-20 17:23:38.065948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7d29981b84'
down_revision = '36f7c7f5c935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema='league_manager') as batch_op:
        batch_op.add_column(sa.Column('resolved_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_review', schema='league_manager') as batch_op:
        batch_op.drop_column('resolved_on')

    # ### end Alembic commands ###
