"""added current period column to player_match_stats

Revision ID: d17800ffef4f
Revises: be15b41156b6
Create Date: 2024-04-17 10:52:28.595546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17800ffef4f'
down_revision = 'be15b41156b6'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.drop_column('current_period')

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

