"""empty message

Revision ID: db2fc555229e
Revises: 2cb390c058b1
Create Date: 2024-03-23 19:41:15.460593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db2fc555229e'
down_revision = '2cb390c058b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('player_match_data_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['reviewed_by_id'], ['id'])
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_match_data_ibfk_3', 'user', ['reviewed_by'], ['id'])
        batch_op.drop_column('reviewed_by_id')

    # ### end Alembic commands ###
