"""converted season datetime columns to date

Revision ID: f8e3e4161023
Revises: b9ccb8cf35b8
Create Date: 2024-03-29 12:22:53.186853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8e3e4161023'
down_revision = 'b9ccb8cf35b8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('finals_start',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('finals_end',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.alter_column('finals_end',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('finals_start',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###


def upgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_api_access():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

