"""added srlm_access column to api_access.authorized_app

Revision ID: fcffbcbd07ab
Revises: be7d29981b84
Create Date: 2024-06-05 19:10:32.883517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcffbcbd07ab'
down_revision = 'be7d29981b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorized_app', schema='api_access') as batch_op:
        batch_op.add_column(sa.Column('srlm_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorized_app', schema='api_access') as batch_op:
        batch_op.drop_column('srlm_access')

    # ### end Alembic commands ###
