#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgresql_ready() {
python << END
import sys

import pymysql
import psycopg2
import os

try:
    endpoint_id = os.getenv('POSTGRES_ENDPOINT')
    if endpoint_id:
          psycopg2.connect(
          dbname='league_manager_api',
          user=os.getenv('POSTGRES_USER'),
          password=os.getenv('POSTGRES_PASS'),
          host=os.getenv('POSTGRES_HOST'),
          port=os.getenv('POSTGRES_PORT'),
          sslmode=os.getenv('POSTGRES_SSL_MODE'),
          options=f'endpoint={endpoint_id}'
      )
    else:
      psycopg2.connect(
          dbname='league_manager_api',
          user=os.getenv('POSTGRES_USER'),
          password=os.getenv('POSTGRES_PASS'),
          host=os.getenv('POSTGRES_HOST'),
          port=os.getenv('POSTGRES_PORT'),
          sslmode=os.getenv('POSTGRES_SSL_MODE')
      )
except psycopg2.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until postgresql_ready; do
  >&2 echo 'Waiting for PostgreSQL Database to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL Database is available'

exec "$@"