#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

mysql_ready() {
python << END
import sys

import pymysql
import urllib.parse as urlparse
import os

url = urlparse.urlparse(os.environ['DATABASE_URL'])
dbname = os.environ['LEAGUE_MANAGER_DB']
user = url.username
password = url.password
host = url.hostname
port = url.port

try:
    pymysql.connect(
        database=dbname,
        user=user,
        password=password,
        host=host,
        port=port
    )
except pymysql.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"